export const states = {
  AL: { state: 'Alabama', demonym: 'Alabamian' },
  AK: { state: 'Alaska', demonym: 'Alaskan' },
  AZ: { state: 'Arizona', demonym: 'Arizonan' },
  AR: { state: 'Arkansas', demonym: 'Arkansan' },
  CA: { state: 'California', demonym: 'Californian' },
  CO: { state: 'Colorado', demonym: 'Coloradan' },
  CT: { state: 'Connecticut', demonym: 'Connecticuter' },
  DE: { state: 'Delaware', demonym: 'Delawarean' },
  FL: { state: 'Florida', demonym: 'Floridian' },
  GA: { state: 'Georgia', demonym: 'Georgian' },
  HI: { state: 'Hawaii', demonym: 'Islander' },
  ID: { state: 'Idaho', demonym: 'Idahoan' },
  IL: { state: 'Illinois', demonym: 'Illinoisan' },
  IN: { state: 'Indiana', demonym: 'Hoosier' },
  IA: { state: 'Iowa', demonym: 'Iowan' },
  KS: { state: 'Kansas', demonym: 'Kansan' },
  KY: { state: 'Kentucky', demonym: 'Kentuckian' },
  LA: { state: 'Louisiana', demonym: 'Louisianian' },
  ME: { state: 'Maine', demonym: 'Mainer' },
  MD: { state: 'Maryland', demonym: 'Marylander' },
  MA: { state: 'Massachusetts', demonym: 'Massachusettsan' },
  MI: { state: 'Michigan', demonym: 'Michiganian' },
  MN: { state: 'Minnesota', demonym: 'Minnesotan' },
  MS: { state: 'Mississippi', demonym: 'Mississippian' },
  MO: { state: 'Missouri', demonym: 'Missourian' },
  MT: { state: 'Montana', demonym: 'Montanan' },
  NE: { state: 'Nebraska', demonym: 'Nebraskan' },
  NV: { state: 'Nevada', demonym: 'Nevadan' },
  NH: { state: 'New Hampshire', demonym: 'New Hampshirite' },
  NJ: { state: 'New Jersey', demonym: 'New Jerseyan' },
  NM: { state: 'New Mexico', demonym: 'New Mexican' },
  NY: { state: 'New York', demonym: 'New Yorker' },
  NC: { state: 'North Carolina', demonym: 'North Carolinian' },
  ND: { state: 'North Dakota', demonym: 'North Dakotan' },
  OH: { state: 'Ohio', demonym: 'Ohioan' },
  OK: { state: 'Oklahoma', demonym: 'Oklahoman' },
  OR: { state: 'Oregon', demonym: 'Oregonian' },
  PA: { state: 'Pennsylvania', demonym: 'Pennsylvanian' },
  RI: { state: 'Rhode Island', demonym: 'Rhode Islander' },
  SC: { state: 'South Carolina', demonym: 'South Carolinian' },
  SD: { state: 'South Dakota', demonym: 'South Dakotan' },
  TN: { state: 'Tennessee', demonym: 'Tennessean' },
  TX: { state: 'Texas', demonym: 'Texan' },
  UT: { state: 'Utah', demonym: 'Utahn' },
  VT: { state: 'Vermont', demonym: 'Vermonter' },
  VA: { state: 'Virginia', demonym: 'Virginian' },
  WA: { state: 'Washington', demonym: 'Washingtonian' },
  WV: { state: 'West Virginia', demonym: 'West Virginian' },
  WI: { state: 'Wisconsin', demonym: 'Wisconsinite' },
  WY: { state: 'Wyoming', demonym: 'Wyomingite' },
};
